name: Build Tweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install ldid
          # تحميل الـ Theos الأساسي
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
          # تحميل الـ SDK الخاص بنظام iOS مباشرة كملف مضغوط لتجنب خطأ 128
          mkdir -p ~/theos/sdks
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip master.zip
          mv sdks-master/* ~/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make clean
          make FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
