name: Build Tweak

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build
        run: |
          export THEOS=~/theos
          make clean
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: OneStateMoumenMod
          path: packages/
